     Exercise

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [9]:
# 6x6 nuumpy array
arr6x6=np.arange(50)
random_int=np.random.randint(1,50, (6, 6))
arr_3d=random_int[:2, -3]
even_numbers=arr_3d[arr_3d % 2 == 0]
print("random array:\n",arr6x6)
print ("random\n",random_int)
print("3d array\n",arr_3d)
print("even number\n",even_numbers)



random array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
random
 [[ 3 10  8 44  2 36]
 [43 24 19 48 42 36]
 [ 7  5 14 43 20 27]
 [26 29 35  2 45 20]
 [34 18 12 49 43  5]
 [16 47  2  1 26 48]]
3d array
 [44 48]
even number
 [44 48]


**question 2**

In [10]:
#Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array
row_1=random_int[:2, :]
print("row 1\n",row_1)
column_1=random_int[:, -3:]
print("column\n",column_1)
even_numbers=random_int[random_int % 2 ==0]
print("even number:\n",even_numbers)


row 1
 [[ 3 10  8 44  2 36]
 [43 24 19 48 42 36]]
column
 [[44  2 36]
 [48 42 36]
 [43 20 27]
 [ 2 45 20]
 [49 43  5]
 [ 1 26 48]]
even number:
 [10  8 44  2 36 24 48 42 36 14 20 26  2 20 34 18 12 16  2 26 48]


Questiion 3

# Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [11]:
arr_reshape=random_int.reshape(3, 2, 6)
print("Reshaped to:\n",arr_reshape)

Reshaped to:
 [[[ 3 10  8 44  2 36]
  [43 24 19 48 42 36]]

 [[ 7  5 14 43 20 27]
  [26 29 35  2 45 20]]

 [[34 18 12 49 43  5]
  [16 47  2  1 26 48]]]


**question 4**
# Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.


In [12]:
identity_mat= np.eye(4)
print("identity matrix;\n",identity_mat)
diagonal=np.arange(10, 40, 10)
print("diagonal num:\n",diagonal)
diag_replace=np.diag([10,20, 30, 40])
print("replace diag:\n",diag_replace)


identity matrix;
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
diagonal num:
 [10 20 30]
replace diag:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


question5
# Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [13]:
range_3x4=np.arange(10)
print("range:\n",range_3x4)
a=np.random.randint(1,10,(3, 4))
print("A:\n",a)
range_4x3=np.arange(10)
print("range:\n",range_4x3)
b=np.random.randint(1,10,(4, 3))
print("B:\n",b)
result=np.dot(a,b)
print("Result:\n",result)

range:
 [0 1 2 3 4 5 6 7 8 9]
A:
 [[7 1 1 6]
 [3 7 6 7]
 [4 9 4 8]]
range:
 [0 1 2 3 4 5 6 7 8 9]
B:
 [[2 1 5]
 [9 3 2]
 [5 6 5]
 [9 2 6]]
Result:
 [[ 82  28  78]
 [162  74 101]
 [181  71 106]]


Question 6
# Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [14]:
#defining a function
def array_2d(arr):
    transform_arr=np.where(arr%2==0,arr**2,-1)
    return transform_arr
new_array=array_2d(result)
print("transformed:\n",new_array)


    
    


transformed:
 [[ 6724   784  6084]
 [26244  5476    -1]
 [   -1    -1 11236]]
